dbconfiglist:
  dbconfig:
    - cfg: "jdbc:mysql://10.168.16.122:6688/etldb|com.mysql.jdbc.Driver|useretl|123qwe123qwe|etldb|py-test-mysql"
    - cfg: "jdbc:mysql://47.98.143.61:3306/hive|com.mysql.jdbc.Driver|root|111111|hive|py-test-mysql"
    - cfg: "jdbc:oracle:thin:@10.168.16.211:1521/devpr|oracle.jdbc.driver.OracleDriver|cashier|cashier|devpr|py-test-oracle"
